baseURL = "https://lameld.github.io"
languageCode = "en-us"
title = "LaMelD's dev Story"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Kakao"
    url = "/kakao/"
    weight = 2

[[menu.main]]
    name = "Swea"
    url = "/swea/"
    weight = 3

[[menu.main]]
    name = "Study"
    url = "/study/"
    weight = 4

[params]
  google_analytics_id=""
  homepage_button_link_kakao = '/kakao'
  homepage_button_text_kakao = 'kakao 문제 풀이'
  homepage_button_link_swea = '/swea'
  homepage_button_text_swea = 'SWexpertAcademy 문제 풀이'
  homepage_button_link_study = '/study'
  homepage_button_text_study = 'Study 자료'
  homepage_intro = '이 블로그의 설명을 담겠습니다.'
  homepage_image = '/images/terminal.gif'
  # 폴더를 추가하려면 아래에 등록하세요
  mainSections = ['kakao', 'swea', 'study']

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
